# Generated by Django 5.2.5 on 2025-10-23 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=14, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=11, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('date_birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, default='', upload_to='client/covers/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
