# Generated by Django 5.2.5 on 2025-09-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='client/covers/%Y/%m/%d/'),
        ),
    ]
