# Generated by Django 5.2.5 on 2025-10-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_birth',
        ),
    ]
