# Generated by Django 5.2.5 on 2026-01-06 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_address_city_client_address_neighborhood_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
