# Generated by Django 5.2.5 on 2026-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_first_name_client_last_name_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sobrenome'),
        ),
    ]
