# Generated by Django 5.2.5 on 2026-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_client_first_name_remove_client_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Crédito'),
        ),
    ]
