# Generated by Django 5.2.5 on 2025-10-23 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('brand', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('packaging_type', models.CharField(blank=True, default='Caixa', max_length=64, null=True)),
                ('unit_measure', models.CharField(blank=True, choices=[('UN', 'Unidade'), ('L', 'Litro'), ('KG', 'Kilograma'), ('G', 'Grama'), ('ML', 'Mililitro'), ('GR', 'Grão')], default='UN', max_length=64, null=True)),
                ('unit_per_packaging', models.IntegerField(default=1)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_stock', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('in_catalog', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='inventory/covers/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
        ),
    ]
