# Generated by Django 5.2.5 on 2025-11-07 03:17

from django.db import migrations


def copy_product_to_stock(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Stock = apps.get_model('inventory', 'Stock')

    for product in Product.objects.all():
        Stock.objects.get_or_create(
            product=product,
            defaults={
                'quantity': getattr(product, 'stock_quantity', 0),
                'minimum_stock': getattr(product, 'minimum_stock', 0),
                'purchase_price': getattr(product, 'purchase_price', 0),
                'sale_price': getattr(product, 'sale_price', 0),
                'wholesale_price': getattr(product, 'wholesale_price', 0),
                'discount': getattr(product, 'discount', 0),
                'due_date': getattr(product, 'due_date', None),
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock'),
    ]

    operations = [
        migrations.RunPython(copy_product_to_stock),
    ]
