# Generated by Django 5.2.5 on 2025-11-24 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_discount_remove_product_minimum_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='due_date',
        ),
    ]
