# Generated by Django 5.2.5 on 2025-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimun_stock',
            field=models.IntegerField(default=0),
        ),
    ]
