# Generated by Django 5.2.5 on 2025-08-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_minimun_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
