# Generated by Django 5.2.5 on 2025-08-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_catalog',
            field=models.BooleanField(default=False),
        ),
    ]
