# Generated by Django 5.2.5 on 2026-01-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='inventory/covers/%Y/%m/%d/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_catalog',
            field=models.BooleanField(default=False, verbose_name='Em catálogo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, default='Caixa', max_length=64, null=True, verbose_name='Tipo de embalagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('L', 'Litro'), ('KG', 'Kilograma'), ('G', 'Grama'), ('ML', 'Mililitro'), ('GR', 'Grão')], default='UN', max_length=64, null=True, verbose_name='Unidade de medida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_per_packaging',
            field=models.IntegerField(default=1, verbose_name='Unidades por embalagem'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minimum_stock',
            field=models.IntegerField(default=0, verbose_name='Estoque mínimo'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de compra'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de venda'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de venda em lote'),
        ),
    ]
