# Generated by Django 5.2.5 on 2026-01-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_barcode_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
    ]
