# Generated by Django 5.2.5 on 2025-08-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='inventory/covers/%Y/%m/%d/'),
        ),
    ]
