# Generated by Django 5.2.5 on 2026-01-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrintTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Etiqueta de produto',
                'verbose_name_plural': 'Etiquetas de produto',
            },
        ),
    ]
