# Generated by Django 5.2.5 on 2025-09-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('KG', 'Kilograma'), ('L', 'Litro'), ('ML', 'Mililitro'), ('PC', 'Pacote'), ('UN', 'Unidade'), ('CX', 'Caixa'), ('FD', 'Fardo')], max_length=255, null=True),
        ),
    ]
