# Generated by Django 5.2.5 on 2026-01-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_productprinttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprinttag',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
    ]
