# Generated by Django 5.2.5 on 2025-09-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
