# Generated by Django 5.2.5 on 2026-01-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_productprinttag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprinttag',
            name='description',
        ),
    ]
