# Generated by Django 5.2.5 on 2025-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_product_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/covers/%Y/%m/%d/'),
        ),
    ]
