# Generated by Django 5.2.5 on 2026-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_productprinttag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprinttag',
            name='resume_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productprinttag',
            name='use_resume_name',
            field=models.BooleanField(default=False),
        ),
    ]
