# Generated by Django 5.2.5 on 2026-02-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_productprinttag_resume_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
