# Generated by Django 5.2.5 on 2025-10-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='minimun_stock',
            new_name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, default='Caixa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_per_packaging',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
