# Generated by Django 5.2.5 on 2026-02-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='discount',
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço de compra'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço de venda'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço de venda em lote'),
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome do grupo')),
                ('product_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='inventory.product', verbose_name='Produto relacionado')),
            ],
            options={
                'verbose_name': 'Grupo de produtos',
                'verbose_name_plural': 'Grupos de produtos',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productgroup'),
        ),
    ]
