# Generated by Django 5.2.5 on 2026-02-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_stock_discount_alter_stock_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='product_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produto relacionado'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='inventory.productgroup', verbose_name='Grupo de produtos'),
        ),
    ]
