# Generated by Django 5.2.5 on 2025-10-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_category_name_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
