# Generated by Django 5.2.5 on 2025-10-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('L', 'Litro'), ('KG', 'Kilograma'), ('G', 'Grama'), ('ML', 'Mililitro'), ('GR', 'Grão')], default='UN', max_length=64, null=True),
        ),
    ]
