# Generated by Django 5.2.5 on 2025-10-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_product_unit_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
