# Generated by Django 5.2.5 on 2025-11-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_remove_order_total_order_total_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='subtotal',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='percentage_discount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
