# Generated by Django 5.2.5 on 2025-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='dinheiro', max_length=255),
        ),
    ]
