# Generated by Django 5.2.5 on 2025-11-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_alter_order_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=50),
        ),
    ]
