# Generated by Django 5.2.5 on 2025-12-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_due_date'),
        ('sale', '0014_rename_discount_sale_total_discount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleItems',
            new_name='SaleItem',
        ),
    ]
