# Generated by Django 5.2.5 on 2025-12-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0017_saleitem_discount_saleitem_percentage_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.CharField(blank=True, default='Consumidor Final', max_length=255),
        ),
    ]
