# Generated by Django 5.2.5 on 2025-12-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0018_sale_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartão', 'Cartão'), ('pix', 'Pix')], default='dinheiro', max_length=255),
        ),
    ]
