# Generated by Django 5.2.5 on 2025-12-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0019_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
