# Generated by Django 5.2.5 on 2025-12-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0020_alter_saleitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='percentage_discount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='total_price',
        ),
    ]
