# Generated by Django 5.2.5 on 2025-12-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0022_alter_saleitem_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_discount',
            new_name='discount',
        ),
    ]
