# Generated by Django 5.2.5 on 2025-12-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0023_rename_total_discount_sale_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
