# Generated by Django 5.2.5 on 2025-12-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0024_sale_freight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='subtotal',
        ),
    ]
