# Generated by Django 5.2.5 on 2025-12-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0025_rename_price_sale_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('sem pagamento', 'Sem Pagamento'), ('dinheiro', 'Dinheiro'), ('cartão', 'Cartão'), ('pix', 'Pix')], default='sem pagamento', max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
