# Generated by Django 5.2.5 on 2026-01-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0027_alter_cart_user_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item de Carrinho', 'verbose_name_plural': 'Itens de Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Itens de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Item de Venda', 'verbose_name_plural': 'Itens de Venda'},
        ),
    ]
