# Generated by Django 5.2.5 on 2026-02-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0029_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='modality',
            field=models.CharField(choices=[('retail', 'Varejo'), ('wholesale', 'Atacado')], default='retail', max_length=50, verbose_name='Modalidade'),
        ),
    ]
