# Generated by Django 5.2.5 on 2026-01-30 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de despesa',
                'verbose_name_plural': 'Tipos de despesas',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('R', 'Varejo'), ('W', 'Atacado')], max_length=1)),
                ('pay_by', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('payday', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('D', 'Pago'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('payment_method', models.CharField(choices=[('C', 'Cartão de crédito'), ('D', 'Cartão de débito'), ('M', 'Dinheiro'), ('B', 'Transferência bancária')], default='M', max_length=1)),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('proof', models.ImageField(blank=True, default='', upload_to='finances/proofs/%Y/%m/%d/', verbose_name='Comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.kind')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
