# Generated by Django 5.2.5 on 2026-02-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='modality',
            field=models.CharField(choices=[('R', 'Varejo'), ('W', 'Atacado'), ('O', 'Outro')], max_length=1),
        ),
    ]
